### ISSUE TITLE
diff-hl mode is not turned on in org files

### ISSUE THREAD

**Issue by hisnawi** [dgutov/diff-hl#91] opened 2017-07-01 21:03 UTC
This is my setup:

```
  (use-package diff-hl
    :ensure t
    :diminish " D"
    :config
    ;; Highlight changed files in the fringe of Dired
    (add-hook 'dired-mode-hook 'diff-hl-dired-mode)
    (global-diff-hl-mode)
    ;;(add-hook 'org-mode-hook 'diff-hl-mode)
    ;; Fall back to the display margin, if the fringe is unavailable
    (unless (display-graphic-p) (diff-hl-margin-mode))
    ;; Highlight changes to the current file in the fringe
    (setq diff-hl-fringe-bmp-function 'diff-hl-fringe-bmp-from-type)
    ;; Right fringe
    (diff-hl-margin-mode)
    (setq diff-hl-margin-side 'right)
    )

```

When opening an org file in git repo diff-hl is not enabled. I had to un-comment the line:

`    ;;(add-hook 'org-mode-hook 'diff-hl-mode)
`
So it gets loaded.

Shouldn't  (global-diff-hl-mode) take care of enabling diff-hl in all buffers?

**Comment by dgutov** [comment] 2017-07-01 21:10
> Shouldn't (global-diff-hl-mode) take care of enabling diff-hl in all buffers?

Sure. As long as the buffer is visiting a file. Can you reproduce the problem without `use-package`?

**Comment by hisnawi** [comment] 2017-07-01 21:20
Same problem. This is the setup I used outside of use-package:

```
  (add-hook 'dired-mode-hook 'diff-hl-dired-mode)
  (global-diff-hl-mode)
  ;;(add-hook 'org-mode-hook 'diff-hl-mode)
  ;; Fall back to the display margin, if the fringe is unavailable
  (unless (display-graphic-p) (diff-hl-margin-mode))
  ;; Highlight changes to the current file in the fringe
  (setq diff-hl-fringe-bmp-function 'diff-hl-fringe-bmp-from-type)
  ;; Right fringe
  (diff-hl-margin-mode)
  (setq diff-hl-margin-side 'right)

```

**Comment by dgutov** [comment] 2017-07-01 21:38
I'm not seeing the problem.

Does `buffer-file-name` evaluate to non-nil in the said org file buffer? What does `diff-hl-mode` evaluate to, when you just visited the file?

**Comment by hisnawi** [comment] 2017-07-01 21:47
Interesting. I was running on emacs24.5, just updated to 25.2 and the problem is gone.

**Comment by dgutov** [comment] 2017-07-01 21:52
IIRC, there were some internal changes in 25 in how minor modes are enabled.

**Comment by seagle0128** [comment] 2017-07-07 09:42
I encountered the similar issue with Emacs 25.2 on Windows. diff-hl doesn't work somehow. I didn't do any change and no highlights suddenly :( very strange...

**Comment by dgutov** [comment] 2017-07-07 12:51
@seagle0128 Does that happen in 25.2 but not in 25.1? Or does some new version of `diff-hl` cause that?

**Comment by dgutov** [comment] 2017-07-07 14:00
Does the problem occur in org files only?

**Comment by seagle0128** [comment] 2017-07-07 14:10
@dgutov it does happen in Emacs 25.2 on Windows and not sure 25.1. I upgraded some packages including diff-hl, but all look good in my macOS. This issue insists for all files. I encountered twice, and it worked again somehow at the first time.

**Comment by dgutov** [comment] 2017-07-07 14:17
@seagle0128 Is there a way you can test it on Windows in 25.1?

And/or can you reproduce the issue starting with `emacs -Q -L path/to/diff-hl`, without other packages?

**Comment by seagle0128** [comment] 2017-07-07 17:08
@dgutov I will try to test and update with you.

**Comment by seagle0128** [comment] 2017-07-10 05:04
I tested with Emacs 25.1 x64 on Windows. The issue still exists. Would you please let me know the troubleshooting steps or logs? I can try and provide more information.

**Comment by dgutov** [comment] 2017-07-10 23:08
First, you launch `emacs -Q -L ~/.emacs.d/elpa/diff-hl-VERSION`, then evaluate 

```
(require 'diff-hl')
(global-diff-hl-mode)
```

in the scratch buffer. And try to see whether it works in Org files in that session.

**Comment by seagle0128** [comment] 2017-07-11 02:37
@dgutov Following the steps, `diff-hl-mode` and `global-diff-hl-mode` work well.
I found some clues. After enabling `diff-hl-flydiff-mode`.  `diff-hl-mode` doesn't work. No diff color on the fringe.  But it works well on macOS and Linux. (GNU Emacs 24.5 and 25.2).

**Comment by dgutov** [comment] 2017-07-11 16:45
All right.

Are you saying that `diff-hl-flydiff-mode` does not work on Windows? But it starts working in Org files if you `(add-hook 'org-mode-hook 'diff-hl-mode)`?

**Comment by seagle0128** [comment] 2017-07-12 02:25
Correct. Actually `diff-hl-mode` works for all files. `diff-hl-flydiff-mode` has some issues on Windows. I remember it was good before.

**Comment by dgutov** [comment] 2017-07-12 10:12
I'm confused because an extra invocation of `diff-hl-mode` (from the said hook) should be basically a no-op. `diff-hl-flydiff-mode` is a global mode which modifies how the former works. You don't switch between the two.

> diff-hl-flydiff-mode has some issues on Windows. I remember it was good before.

It hasn't changed in quite a while, though. Could you try `git bisect`?

**Comment by seagle0128** [comment] 2017-07-14 02:46
I revert `diff-hl` to 1.8.4 and the issue is still there.
This morning, I upgrade `flycheck` and the issue disappears!!!
I close it and keep my eyes on there. Thanks for your help!

**Closed** 2017-11-18 23:12 UTC
