### ISSUE TITLE
Emacs 25 segfaults when running diff-hl-mode

### ISSUE THREAD

**Issue by pksadiq** [dgutov/diff-hl#74] opened 2016-08-15 05:00 UTC
My .emacs:

(package-initialize)
(when (fboundp 'set-fringe-mode)
  (set-fringe-mode '(0 . 0))
  (add-hook 'c-mode-common-hook
            (lambda ()
              (setq left-fringe-width 4
                    right-fringe-width 0))))

I have installed diff-hl-mode from gnu elpa (version 1.8.4)

How to reproduce:
1. Open some .c file from some git repository (the file should already be added, so 'git diff' shows the changes)
2.  M-x diff-hl-mode
3. Modify the file (if diff-hl-flydiff-mode is enabled, GNU Emacs segfaults here)
4. Saving the file segfaults Emacs

[emacs.debug.txt](https://github.com/dgutov/diff-hl/files/417540/emacs.debug.txt)

**Comment by dgutov** [comment] 2016-08-16 00:40
Hi! Thanks filing the issue, but a segfault means a bug in Emacs.

So please make sure that you're using the latest version from the branch you're testing, and if the problem is present there, `M-x report-emacs-bug`. Please fill in the details, send the report, and answer any follow-up questions the developers might ask you.

**Comment by pksadiq** [comment] 2016-08-16 01:01
OK. Thanks for the reply. I shall do when time allows me.

Thank you

**Comment by dgutov** [comment] 2016-08-16 08:00
Please keep in mind that Emacs 25 could be released in a week or two, if no blocker bugs come up.

**Closed** 2017-06-17 00:35 UTC
Labels: invalid
