### ISSUE TITLE
Error running timer ‘track-changes--call-signal’: (cl-assertion-failed (eq tracker diff--track-changes))

### ISSUE THREAD

**Issue by sudo-human** [dgutov/diff-hl#218] opened 2024-04-15 18:37 UTC
While using `diff-hl-flydiff-mode` mode, the following message is printed again and again in the echo area (*Messages* buffer)
`Error running timer ‘track-changes--call-signal’: (cl-assertion-failed (eq tracker diff--track-changes))`

**Comment by dgutov** [comment] 2024-04-15 22:01
It might be fixed now, try updating to the latest.

**Comment by LemonBreezes** [comment] 2024-04-16 21:35
> It might be fixed now, try updating to the latest.

I am still getting the issue with everything updated. The Emacs 30 commit I am on is 1be21dd95388037cfb71474a1fbd2a7d3583a80a.

**Comment by dgutov** [comment] 2024-04-16 21:46
All right, thanks, I can reproduce it too.

That's still the same original cause (a recent change) that apparently hasn't been addressed in full yet.

You can try filing a bug to get a more prompt resolution (`M-x report-emacs-bug`), but either way I'll look into it as soon as I have the time.

**Comment by Vonfry** [comment] 2024-04-21 08:34
I update the emacs to the 3dfca6f9c7f4da512fff48cf6957c6492e2c0449 today, and this error disappears for me.

**Comment by LemonBreezes** [comment] 2024-04-21 19:56
> I update the emacs to the 3dfca6f9c7f4da512fff48cf6957c6492e2c0449 today, and this error disappears for me.

Same for me.

**Comment by dgutov** [comment] 2024-04-21 21:52
Looks like this got fixed in https://github.com/emacs-mirror/emacs/commit/71d2ec7aba3.

Thanks for testing!

**Closed by dgutov** 2024-04-21 21:52 UTC
